@echo off
echo Compiling UiShell.o...
gcc.exe -c dllmain.c -o dllmain.o -lgdi32 -DBUILDING_DLL=1 --verbose
echo Wrapping UiShell.dll...
dllwrap.exe --output-def libUiShell.def --implib libUiShell.a dllmain.o -static-libstdc++ -static-libgcc dwmapi.dll -lgdi32 --no-export-all-symbols --add-stdcall-alias -o UiShell.dll